language: java
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
addons:
    postgresql: "9.3"

# go faster on travis
sudo: false

# stop mvn install from running
install: true

script: mvn -B -V package javadoc:javadoc test
