language: java
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
addons:
    postgresql: "9.5"

# go faster on travis
sudo: false

# stop mvn install from running
install: true

script: mvn -B -V package javadoc:javadoc test

after_success:
    - mvn -B -V clean test jacoco:report coveralls:report
